### ISSUE TITLE
Buttons appear blank

### ISSUE THREAD

**Issue by aaronahearne** [mvnobrega/nova-texteditor#1]
Buttons appear blank in the editor.

Nova version: 3.11
PHP Version: 7.4.5

![image](https://user-images.githubusercontent.com/5104743/94834351-2c097980-0408-11eb-80f1-4c2257c2dcbd.png)

**Comment by dbateson** [comment]
same issue. How did you fix it?

**Comment by Muetze42** [comment]
This package is not complete. It's missing asset publishing.

Copy `vendor/mvnobrega/nova-texteditor/dist/fonts/vendor/icons.svg` to `public/fonts/vendor/trumbowyg/dist/ui/icons.svg`
